sample_type:
  - "Core"
  - "Core Half Round"
  - "Core Piece"
  - "Core Quarter Round"
  - "Core Section"
  - "Core Section Half"
  - "Core Sub-Piece"
  - "Core Whole Round"
  - "CTD"
  - "Cuttings"
  - "Dredge"
  - "Grab"
  - "Hole"
  - "Individual Sample"
  - "Oriented Core"
  - "Other"
  - "Rock Powder"
  - "Site"
  - "Terrestrial Section"
  - "Trawl"
